# Generated by Django 2.1.3 on 2019-01-17 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockQueryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=32, unique=True)),
                ('company', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=45)),
                ('spec', models.CharField(blank=True, max_length=200, null=True)),
                ('q_quantity', models.PositiveSmallIntegerField()),
                ('s_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('q_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
